export enum Status {
  UPCOMING = 'UPCOMING',
  INCOMPLETE = 'INCOMPLETE',
  COMPLETE = 'COMPLETE',
  INVOICED = 'INVOICED',
  PAID = 'PAID',
}

export enum Category {
  LOCKS_AND_HARDWARE = 'LOCKS_AND_HARDWARE',
  SHELVING = 'SHELVING',
  SHOWER_ENCLOSURES = 'SHOWER_ENCLOSURES',
  MIRRORS = 'MIRRORS',
  OTHER = 'OTHER',
}

export enum Role {
  USER = 'USER',
  ADMIN = 'ADMIN',
}